[build]
publish = "web/dist"
command = "npm ci --prefix web && npm run build --prefix web"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://REPLACE_WITH_RENDER_URL/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


