[build]
  command = "npm ci && npm run build"
  publish = "dist"
  base = "."

[[redirects]]
  from = "/api/*"
  to = "https://REPLACE_WITH_RENDER_URL/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


